version: '3.7'
services:
  db:
    image: mysql:8.0.32
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${SPRING_DATASOURCE_ROOT_PASSWORD}"
      MYSQL_DATABASE: todo
      MYSQL_USER: "${SPRING_DATASOURCE_USERNAME}"
      MYSQL_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  app:
    image: tomcat
    container_name: app
    restart: always
    depends_on:
      - db
    volumes:
      - ./target/todo-project.war:/usr/local/tomcat/webapps/ROOT.war
    ports:
      - "8080:8080"
    environment:
      MYSQL_ROOT_PASSWORD: "${SPRING_DATASOURCE_ROOT_PASSWORD}"
      MYSQL_DATABASE: todo
      MYSQL_USER: "${SPRING_DATASOURCE_USERNAME}"
      MYSQL_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
