version: '3.7'
services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      MYSQL_ROOT_PASSWORD: "${SPRING_DATASOURCE_ROOT_PASSWORD}"
      MYSQL_DATABASE: todo
      MYSQL_USER: "${SPRING_DATASOURCE_USERNAME}"
      MYSQL_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"